// apps/news-site/news-site-next-pages-router/src/components/organisms/section/section.jsx
import Article from "@/partials/article/article";

import { useDataContext } from "@/context/data-context";

import styles from "news-site-css/dist/layout.module.css";
import { Fragment } from "react";

export default function Section({ section, sectionIndex, pageId }) {
    const { config } = useDataContext();
    const ad = config?.ads?.[pageId].articles?.[sectionIndex];

    return (
        <>
            {section.name
                ? <div id={section.id} className={styles["row-header"]}>
                    <h2>{section.name}</h2>
                </div>
                : null}
            <section className={styles.row}>
                {section.articles.map((article, index) =>
                    <Fragment key={article.id}>
                        <Article article={article} sectionIndex={sectionIndex} pageId={pageId} ad={index === section.articles.length - 1 ? ad : null} />
                    </Fragment>
                )}
            </section>
        </>
    );
}

// apps/news-site/news-site-nuxt-pages-router/components/organisms/Section.vue
<script setup>
import { inject } from "vue";
import styles from "news-site-css/dist/layout.module.css";

const data = inject("data");

const { section, sectionIndex, pageId } = defineProps({
    section: Object,
    sectionIndex: Number,
    pageId: String,
});

</script>

<template>
  <div
    v-if="section?.name"
    :id="section.id"
    :class="styles['row-header']"
  >
    <h2>{{ section.name }}</h2>
  </div>
  <section :class="styles.row">
    <Article
      v-for="(article, index) in section.articles"
      :key="article.id"
      :article="article"
      :section-index="sectionIndex"
      :page-id="pageId"
      :ad="index === section.articles.length - 1 ? data.config?.ads?.[pageId].articles?.[sectionIndex] : null"
    />
  </section>
</template>
