// apps/news-site/news-site-nuxt/components/organisms/Layout.vue
<script setup>
import { ref, inject, onMounted } from "vue";
import { useRoute } from "#imports";
import styles from "news-site-css/dist/layout.module.css";

const showMessage = ref(false);
const route = useRoute();

const { content, links } = inject("data");

onMounted(() => {
    showMessage.value = content[route.name].message;
});

const closeMessage = () => {
    showMessage.value = false;
};
</script>

<template>
  <NuxtLink
    :to="`${route.path}#content`"
    class="skip-link"
  >
    {{ links.a11y.skip.label }}
  </NuxtLink>
  <div
    id="page"
    :class="styles.page"
  >
    <Header />
    <Navigation />
    <Message
      v-if="content[route.name].message"
      v-show="showMessage"
      :on-close="closeMessage"
      :message="content[route.name].message"
    />
    <Main>
      <slot />
    </Main>
    <Footer />
  </div>
</template>

// apps/news-site/news-site-next-app-router/src/partials/layout/layout.jsx
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import Link from "next/link";

import Header from "@/partials/header/header";
import Navigation from "@/components/organisms/navigation/navigation";
import Main from "@/components/organisms/main/main";
import Footer from "@/components/organisms/footer/footer";

import { useDataContext } from "@/context/data-context";
import { Message } from "@/components/molecules/message/message";

import styles from "news-site-css/dist/layout.module.css";

export default function Layout({ children, id }) {
    const [showMessage, setShowMessage] = useState(false);
    const { alerts, links } = useDataContext();

    useEffect(() => {
        setShowMessage(alerts[id].message);
    }, [alerts, id]);

    const pageRef = useRef(null);
    const pathname = usePathname();

    function closeMessage() {
        setShowMessage(false);
    }

    return (
        <>
            <Link href={`${pathname}#content`} className="skip-link">
                {links.a11y.skip.label}
            </Link>
            <div className={styles.page} ref={pageRef}>
                <Header />
                <Navigation />
                {showMessage ? <Message message={alerts[id].message} onClose={closeMessage} /> : null}
                <Main>{children}</Main>
                <Footer />
            </div>
        </>
    );
}
