// apps/news-site/news-site-next-pages-router/src/components/molecules/navlist/navlist-item.jsx
import Link from "next/link";
import classNames from "classnames";

import styles from "news-site-css/dist/navbar.module.css";

export default function NavListItem({ id, label, url, callback, itemClass, isActive }) {
    return (
        <li className={classNames(styles["navbar-item"], itemClass)} onClick={callback}>
            <Link href={url} id={id} className={classNames({ [styles.active]: isActive })}>
                {label}
            </Link>
        </li>
    );
}

// apps/news-site/news-site-nuxt/components/atoms/NavlistItem.vue
<script lang="js">
import styles from "news-site-css/dist/navbar.module.css";
export default {
    props: {
        label: String,
        url: String,
        callback: Function,
        id: String,
    },
    data () {
        return {
            styles,
        };
    }
};
</script>

<template>
  <NuxtLink
    :id="id"
    :active-class="styles['active']"
    :to="url"
    @click="callback"
  >
    {{ label }}
  </NuxtLink>
</template>
