// aurora/third-parties/news-site-next-third-party-basic/src/components/molecules/navlist/navlist.jsx
import { useDataContext } from "@/context/data-context";
import Dropdown from "@/components/atoms/dropdown/dropdown";
import NavListItem from "./navlist-item";
import { usePathname } from "next/navigation";

import styles from "news-site-css/dist/navbar.module.css";

export default function NavList({ callback, id }) {
    const { content, buttons } = useDataContext();
    const pathname = usePathname();

    const navItems = [];
    const dropdownItems = [];

    Object.keys(content).forEach((key) => {
        if (content[key].priority === 1)
            navItems.push(key);
        else if (content[key].priority === 2)
            dropdownItems.push(key);
    });

    return (
        <ul className={styles["navbar-list"]}>
            {navItems.map((key) => <NavListItem id={`${id}-${key}-link`} key={key} label={content[key].name} url={content[key].url} callback={callback} isActive={pathname.split("/")[1] === key} />
            )}
            {dropdownItems.length > 0
                ? <li className={styles["navbar-item"]}>
                    <Dropdown animatedIconClass={styles["navbar-label-icon"]} label={buttons.more.label}>
                        {dropdownItems.map((key) =>
                            <NavListItem id={`${id}-${key}-link`} key={key} label={content[key].name} url={content[key].url} callback={callback} itemClass={styles["navbar-dropdown-item"]} isActive={pathname.split("/")[1] === key} />
                        )}
                    </Dropdown>
                </li>
                : null}
        </ul>
    );
}

// apps/news-site/news-site-nuxt/components/atoms/Navlist.vue
<script lang="js">
import { inject } from "vue";
import { useRoute } from "#imports";
import styles from "news-site-css/dist/navbar.module.css";

export default {
    props: {
        callback: Function,
        id: String,
    },
    setup() {
        const { content } = inject("data");

        const navItems = [];
        const dropdownItems = [];

        Object.keys(content).forEach(key => {
            if (content[key].priority === 1)
                navItems.push(key);
            else if (content[key].priority === 2)
                dropdownItems.push(key);
        });

        const route = useRoute();
        return { route, content, navItems, dropdownItems };
    },
    data() {
        return {
            styles,
        };
    }
};
</script>

<template>
  <ul :class="styles['navbar-list']">
    <li
      v-for="key in navItems"
      :key="key"
      :class="styles['navbar-item']"
    >
      <NavlistItem
        :id="`${id}-${key}-link`"
        :label="content[key].name"
        :url="content[key].url"
        :callback="callback"
      />
    </li>
    <li
      v-if="dropdownItems.length > 0"
      :class="styles['navbar-item']"
    >
      <Dropdown :animated-icon-class="styles['navbar-label-icon']">
        <li
          v-for="key in dropdownItems"
          :key="key"
          :class="[styles['navbar-item'], styles['navbar-dropdown-item']]"
        >
          <NavlistItem
            :id="`${id}-${key}-link`"
            :label="content[key].name"
            :url="content[key].url"
            :callback="callback"
          />
        </li>
      </Dropdown>
    </li>
  </ul>
</template>
