// apps/news-site/news-site-nuxt/components/molecules/Header.vue
<script lang="js">
import styles from "news-site-css/dist/header.module.css";
export default {
    data () {
        return {
            styles
        };
    }
};
</script>

<template>
  <header :class="styles['page-header']">
    <NuxtLink
      to="/"
      :class="styles['page-header-title']"
    >
      <TitleIcon />
    </NuxtLink>
  </header>
</template>

// apps/news-site/news-site-next-pages-router/src/partials/header/header.jsx
import Link from "next/link";
import TitleIcon from "@/components/assets/title-icon";

import styles from "news-site-css/dist/header.module.css";

export default function Header() {
    return (
        <header className={styles["page-header"]}>
            <Link href="/" className={styles["page-header-title"]}>
                <TitleIcon />
            </Link>
        </header>
    );
}
