// apps/news-site/news-site-nuxt-pages-router/components/organisms/Dialog.vue
<script setup>
import { inject } from "vue";
import { useLocalStorage } from "#imports";
import styles from "news-site-css/dist/dialog.module.css";

const { onClose } = defineProps({
    onClose: Function,
});

const { language } = inject("data").value;
const { settings } = language.dialog;

const [reduceMotion, setReduceMotion] = useLocalStorage("news-site-settings-reduced-motion", false);
const [highContrast, setHighContrast] = useLocalStorage("news-site-settings-high-contrast", false);

function toggleMotion(e) {
    setReduceMotion(e.target.checked);

    if (e.target.checked)
        document.documentElement.classList.add("reduced-motion");
    else
        document.documentElement.classList.remove("reduced-motion");
}

function toggleContrast(e) {
    setHighContrast(e.target.checked);

    if (e.target.checked)
        document.documentElement.classList.add("forced-colors");
    else
        document.documentElement.classList.remove("forced-colors");
}
</script>

<template>
  <div
    id="settings"
    :class="[styles.dialog, styles.open]"
  >
    <button
      id="close-dialog-link"
      :class="styles['dialog-close-button']"
      title="Close Button"
      @click="onClose"
    >
      <div
        :class="[styles['dialog-close-button-icon'], 'animated-icon', 'close-icon', 'hover']"
        title="Close Icon"
      >
        <span class="animated-icon-inner">
          <span />
          <span />
        </span>
      </div>
    </button>
    <header :class="styles['dialog-header']">
      <h2>{{ settings.header }}</h2>
    </header>
    <section :class="styles['dialog-body']">
      <div :class="styles['dialog-item']">
        <Toggle
          id="motion"
          :label="settings.items.motion.label"
          :on-change="toggleMotion"
          :checked="reduceMotion"
        />
      </div>
      <div :class="styles['dialog-item']">
        <Toggle
          id="contrast"
          :label="settings.items.contrast.label"
          :on-change="toggleContrast"
          :checked="highContrast"
        />
      </div>
    </section>
  </div>
</template>

// apps/news-site/news-site-next-app-router/src/components/dialog/dialog.jsx
import classNames from "classnames";

import Toggle from "../toggle/toggle";
import { useDataContext } from "@/context/data-context";
import { useLocalStorage } from "@/hooks/use-local-storage";

import styles from "news-site-css/dist/dialog.module.css";

export default function Dialog({ onClose }) {
    const [reduceMotion, setReduceMotion] = useLocalStorage("news-site-settings-reduced-motion", false);
    const [highContrast, setHighContrast] = useLocalStorage("news-site-settings-high-contrast", false);
    const { settings } = useDataContext();

    function toggleMotion(e) {
        setReduceMotion(e.target.checked);

        if (e.target.checked)
            document.documentElement.classList.add("reduced-motion");
        else
            document.documentElement.classList.remove("reduced-motion");
    }

    function toggleContrast(e) {
        setHighContrast(e.target.checked);

        if (e.target.checked)
            document.documentElement.classList.add("forced-colors");
        else
            document.documentElement.classList.remove("forced-colors");
    }

    return (
        <div id="settings" className={classNames(styles.dialog, styles.open)}>
            <button id="close-dialog-link" className={styles["dialog-close-button"]} onClick={onClose} title="Close Button">
                <div className={classNames(styles["dialog-close-button-icon"], "animated-icon", "close-icon", "hover")} title="Close Icon">
                    <span className="animated-icon-inner">
                        <span></span>
                        <span></span>
                    </span>
                </div>
            </button>
            <header className={styles["dialog-header"]}>
                <h2>{settings.header}</h2>
            </header>
            <section className={styles["dialog-body"]}>
                <div className={styles["dialog-item"]}>
                    <Toggle id="motion" label={settings.items.motion.label} onChange={toggleMotion} checked={reduceMotion} />
                </div>
                <div className={styles["dialog-item"]}>
                    <Toggle id="contrast" label={settings.items.contrast.label} onChange={toggleContrast} checked={highContrast} />
                </div>
            </section>
        </div>
    );
}
