// apps/news-site/news-site-nuxt/components/atoms/Dropdown.vue
<script setup>
import { ref } from "vue";
import styles from "news-site-css/dist/dropdown.module.css";

const { animatedIconClass } = defineProps({
    animatedIconClass: String,
    label: String
});

const isOpen = ref(false);

function closeDropdown() {
    isOpen.value = false;
}

function handleChange(e) {
    isOpen.value = e.target.checked;
}
</script>

<template>
  <div :class="styles.dropdown">
    <input
      id="navbar-dropdown-toggle"
      type="checkbox"
      :class="styles['dropdown-toggle']"
      :checked="isOpen"
      @change="handleChange"
    >
    <label
      for="navbar-dropdown-toggle"
      :class="styles['dropdown-label']"
    >
      <span :class="styles['dropdown-label-text']">{{ label }}</span>
      <div :class="['animated-icon', 'arrow-icon', 'arrow', animatedIconClass]">
        <span
          class="animated-icon-inner"
          title="Arrow Icon"
        >
          <span />
          <span />
        </span>
      </div>
    </label>
    <ul
      :class="styles['dropdown-content']"
      @click="closeDropdown"
    >
      <slot />
    </ul>
  </div>
</template>

// apps/news-site/news-site-next-pages-router/src/components/atoms/dropdown/dropdown.jsx
import { useState } from "react";
import classNames from "classnames";

import styles from "news-site-css/dist/dropdown.module.css";

export default function Dropdown({ children, animatedIconClass, label }) {
    const [isOpen, setIsOpen] = useState(false);

    function handleChange(e) {
        setIsOpen(e.target.checked);
    }

    function closeDropdown() {
        setIsOpen(false);
    }

    return (
        <div className={styles.dropdown}>
            <input type="checkbox" id="navbar-dropdown-toggle" className={styles["dropdown-toggle"]} onChange={handleChange} checked={isOpen} />
            <label htmlFor="navbar-dropdown-toggle" className={styles["dropdown-label"]}>
                <span className={styles["dropdown-label-text"]}>{label}</span>
                <div className={classNames("animated-icon", "arrow-icon", "arrow", animatedIconClass)}>
                    <span className="animated-icon-inner" title="Arrow Icon">
                        <span></span>
                        <span></span>
                    </span>
                </div>
            </label>
            <ul className={styles["dropdown-content"]} onClick={closeDropdown}>
                {children}
            </ul>
        </div>
    );
}
