// apps/news-site/news-site-nuxt/components/molecules/Header.vue
<script lang="js">
import styles from "news-site-css/dist/header.module.css";
export default {
    data () {
        return {
            styles
        };
    }
};
</script>

<template>
  <header :class="styles['page-header']">
    <NuxtLink
      to="/"
      :class="styles['page-header-title']"
    >
      <TitleIcon />
    </NuxtLink>
  </header>
</template>

// apps/aurora/third-parties/news-site-next-third-party-capital/src/partials/header/header.jsx
import TitleIcon from "@/assets/title-icon";

import styles from "news-site-css/dist/header.module.css";
import { NavLink } from "react-router-dom";

export default function Header() {
    return (
        <header className={styles["page-header"]}>
            <NavLink to="/" className={styles["page-header-title"]}>
                <TitleIcon />
            </NavLink>
        </header>
    );
}
