// apps/news-site/news-site-nuxt/partials/Layout.vue
<script setup>
import { ref, inject, onMounted, watch } from "vue";
import { useRoute } from "#imports";
import styles from "news-site-css/dist/layout.module.css";

const showMessage = ref(false);
const route = useRoute();

const data = inject("data");
const { alerts, links } = data.value;

function handleOnChange() {
    const url = route.path;
    requestIdleCallback(() => {
        window.dispatchEvent(new CustomEvent("route-change-complete", { detail: { url } }));
    });

    showMessage.value = alerts[route.name]?.message ? true : false;
}

onMounted(handleOnChange);
watch(() => route.path, handleOnChange);

const closeMessage = () => {
    showMessage.value = false;
};
</script>

<template>
  <NuxtLink
    :to="`${route.path}#content`"
    class="skip-link"
  >
    {{ links.a11y.skip.label }}
  </NuxtLink>
  <div
    id="page"
    :class="styles.page"
  >
    <Ad
      v-if="data.config?.ads?.[route.name].hero"
      :data="data.config?.ads?.[route.name].hero"
      location="header"
    />
    <Header />
    <Navigation />
    <Message
      v-if="alerts[route.name]?.message"
      v-show="showMessage"
      :on-close="closeMessage"
      :message="alerts[route.name]?.message"
    />
    <Main>
      <slot />
    </Main>
    <Footer />
  </div>
</template>

// apps/news-site/news-site-next/src/partials/layout/layout.jsx
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { HashLink } from "react-router-hash-link";

import Header from "@/partials/header/header";
import Navigation from "@/components/organisms/navigation/navigation";
import Main from "@/components/organisms/main/main";
import Footer from "@/components/organisms/footer/footer";
import Ad from "@/components/atoms/ad/ad";

import { useDataContext } from "@/context/data-context";
import { Message } from "@/components/molecules/message/message";

import styles from "news-site-css/dist/layout.module.css";

export default function Layout({ children, id }) {
    const [showMessage, setShowMessage] = useState(false);
    const { alerts, links, config } = useDataContext();
    const hero = config?.ads?.[id].hero;

    useEffect(() => {
        const url = location.hash;
        requestIdleCallback(() => {
            window.dispatchEvent(new CustomEvent("route-change-complete", { detail: { url } }));
        });
    }, [location.hash]);

    useEffect(() => {
        setShowMessage(alerts[id].message);
    }, [alerts, id]);

    const pageRef = useRef(null);
    const pathname = usePathname();

    function closeMessage() {
        setShowMessage(false);
    }

    return (
        <>
            <HashLink to={`${pathname}#content`} className="skip-link">
                {links.a11y.skip.label}
            </HashLink>
            <div className={styles.page} ref={pageRef}>
                {hero ? <Ad data={hero} location="header" /> : null}
                <Header />
                <Navigation />
                {showMessage ? <Message message={alerts[id].message} onClose={closeMessage} /> : null}
                <Main>{children}</Main>
                <Footer />
            </div>
        </>
    );
}
