// apps/news-site/news-site-nuxt/components/organisms/Section.vue
<script setup>
import styles from "news-site-css/dist/layout.module.css";

const { section } = defineProps({
    section: Object
});
</script>

<template>
  <div
    v-if="section?.name"
    :id="section.id"
    :class="styles['row-header']"
  >
    <h2>{{ section.name }}</h2>
  </div>
  <section :class="styles.row">
    <Article
      v-for="(article) in section.articles"
      :key="article.id"
      :article="article"
    />
  </section>
</template>

// apps/news-site/news-site-next/src/components/organisms/section/section.jsx
import Article from "@/partials/article/article";

import styles from "news-site-css/dist/layout.module.css";

export default function Section({ section }) {
    return (
        <>
            {section.name
                ? <div id={section.id} className={styles["row-header"]}>
                    <h2>{section.name}</h2>
                </div>
                : null}
            <section className={styles.row}>
                {section.articles.map((article) =>
                    <Article key={article.id} article={article} />
                )}
            </section>
        </>
    );
}
